### PR TITLE
Fix assembler

### PR DESCRIPTION
**Pull request by botn365**
fix for  #614

### CODE REVIEW

**Comment by ScriptedPiky** [comment]
Tested various things on the latest CCI 478 build:
Maraging Steel 250 and 300 have been fixed. Checked the other smelting recipes as a precaution, they do not seem to be bugged.
Mixer fully works. Mixer can now properly use fluids and treats input busses far better (I.E. input buses no longer share with each other as intended).
Volcanus can properly smelt things and awakened draconium in particular.
Large Scale Auto-Assembler on `Disassembler` mode now correctly consumes EU. Does not consume regular eggs (possibly a GTNH interaction?), however, it will consume giant chicken eggs as normal.  Properly disassembles machines as intended; tested with LuV voltage, differences may apply. For giant eggs, I can successfully use hoppers to automatically input the eggs inside the input bus. I have not tested with other means like ME or EiO or GT pipes or other means.

If possible, can we have a way to automatically trigger the ticking of giant eggs? So that we may have automated ways of triggering the eggs without player interaction, much like the radioactive containment box triggering radioactive dusts with timed life.

**Comment by Dream-Master** [comment]
@ScriptedPiky Eggs are disabled in Dissasembler in GTNH. Is this a problem ? I want to change steam cells use a better recipe (Bio Vat from Bartworks maybe)

**Comment by ScriptedPiky** [comment]
@Dream-Master Ohhh I was wondering why that didn't work. Merely curious. Would be nice to use the Bio Vat for more usages (too many on the top of my head).

**Comment by draknyte1** [comment]
This right to merge in?

**Comment by Dream-Master** [comment]
@draknyte1 yea merge this and i can throw a new version on zeta this weekend for testing

**Comment by botn365** [comment]
branch can be merged not fixing anything at the moment

**Pull request merged**
